[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.30"
src = "src"
via_ir = false

[rpc_endpoints]
unichain_sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"

[etherscan]
unichain_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://unichain-sepolia.blockscout.com/api" }

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false
